version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Contraseña
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - /mnt/data/var/lib/docker/volumes/sqlserver_data:/var/opt/mssql
      - /mnt/data/var/lib/docker/volumes/sqlserver_system:/var/opt/mssql/.system
      - /mnt/data/var/lib/docker/volumes/sqlserver_log:/log
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped