FROM mcr.microsoft.com/sdk:10.0 AS build-env
WORKDIR /src

COPY . ./

RUN dotnet restore
RUN dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build-env /src/publish ./

ENTRYPOINT ["dotnet", "WebApiNetCore.dll"]